Total Arquivos =
COUNTROWS(results)

Total Anomalias =
COUNTROWS(anomalies)

Arquivos Suspeitos =
CALCULATE(
    DISTINCTCOUNT(results[file_name]),
    results[is_suspect] = "SIM"
)

Arquivos Processados =
CALCULATE(
    DISTINCTCOUNT(results[file_name]),
    results[process_status] = "processed"
)

Arquivos com Falha =
CALCULATE(
    DISTINCTCOUNT(results[file_name]),
    results[process_status] <> "processed"
)

Arquivos via LLM =
CALCULATE(
    DISTINCTCOUNT(results[file_name]),
    results[extraction_source] = "llm"
)

Taxa de Suspeita =
DIVIDE([Arquivos Suspeitos], [Total Arquivos], 0)

Taxa de Falha =
DIVIDE([Arquivos com Falha], [Total Arquivos], 0)

Taxa LLM =
DIVIDE([Arquivos via LLM], [Total Arquivos], 0)

Alertas de Processamento =
CALCULATE(
    DISTINCTCOUNT(anomalies[file_name]),
    anomalies[codigo_anomalia] = "FILE_PROCESSING_ISSUE"
)

Fornecedores Impactados =
DISTINCTCOUNT(anomalies[fornecedor])

Tipos de Anomalia =
DISTINCTCOUNT(anomalies[tipo_anomalia])

Eventos de Auditoria =
COUNTROWS(audit_log)

Providers Distintos =
DISTINCTCOUNT(results[provider])

Prompts Distintos =
DISTINCTCOUNT(results[prompt_version])

Valor Bruto Total =
SUM(results[valor_bruto_num])

Valor Bruto Medio =
AVERAGE(results[valor_bruto_num])

Valor Bruto Suspeito =
CALCULATE(
    SUM(results[valor_bruto_num]),
    results[is_suspect] = "SIM"
)

Percentual de Valor Suspeito =
DIVIDE([Valor Bruto Suspeito], [Valor Bruto Total], 0)

Anomalias Alta Gravidade =
CALCULATE(
    COUNTROWS(anomalies),
    anomalies[gravidade] = "Alta"
)

Anomalias Media Gravidade =
CALCULATE(
    COUNTROWS(anomalies),
    anomalies[gravidade] = "Media"
)

Documentos Pagos =
CALCULATE(
    DISTINCTCOUNT(results[file_name]),
    results[status] = "PAGO"
)

Documentos Cancelados =
CALCULATE(
    DISTINCTCOUNT(results[file_name]),
    results[status] = "CANCELADO"
)

Ultimo Processamento =
MAX(results[processed_at_datetime])

Erros de Encoding =
COUNTROWS(
    FILTER(
        results,
        CONTAINSSTRING(LOWER(results[warnings]), "encoding")
    )
)
